[build]
  base = "_build"
  command = "pip install -r requirements.txt && jupyter-book build ."
  publish = "./_build/html"

[context.deploy-preview]
  ignore = '''
if echo $HEAD | grep "^all-contributors"; then
  return 0
else
  return 1
fi
'''

# A redirect rule with all the supported properties
[[redirects]]
  from = "https://62ab5c8a19bcdd00840a6f7b--gentle-moonbeam-f3167d.netlify.app"
  to = "https://62ab5c8a19bcdd00840a6f7b--gentle-moonbeam-f3167d.netlify.app/welcome"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true
